### ISSUE TITLE
Googleの検索結果に表示される位置情報

### ISSUE THREAD

**Issue by InamuraJIN** [yukinashi/amazon_personal_information_hide#1]
良ければ、Googleの検索結果直下に表示される住所も非表示にしていただけませんでしょうか？
ご検討お願いします

**Comment by fa0311** [comment]
AmazonのURLのみに権限を絞って個人情報を非表示にする拡張機能なのでそれ以上の対応はしません
また、「コンテンツを非表示にする拡張機能」や「カスタムCSSを挿入できる拡張機能」でも同様のことが出来ると思うのでそちらを導入してみてください
